### ISSUE TITLE
Mail icon disappears in OS X dark theme if there are unread emails

### ISSUE THREAD

**Issue by chdsbd** [jashephe/Gmail-Notifier#24]
If there is an unread message count in the menu bar when OS X dark theme is enabled, the mail icon disappears.

<img width="566" alt="ex" src="https://cloud.githubusercontent.com/assets/1929960/9620328/0af2b088-50e7-11e5-8202-6722aa3214c5.png">

**Comment by jashephe** [comment]
Yes, that is indeed true (and of course, not unique to Gmail Notifier).  I fixed this a while ago when Yosemite came out, but I never got around to releasing a new version.  Stand by.

**Comment by chdsbd** [comment]
Wow that was fast. Thanks for the continued support of this great app.

**Comment by jashephe** [comment]
No problem (and as you can see, the relevant commits were actually made back in October; I had just never pushed to Github).  For anyone interested, I *have* been working on a new version for a few months, which is a ground-up rewrite in Swift (for a variety of reasons, including the fact that the version of ReactiveCocoa we target is no longer supported).  However, since I'm a student and this is one of many hobby projects, progress is slow.
