### ISSUE TITLE
Go to Directly to Inbox for Given Email

### ISSUE THREAD

**Issue by fny** [jashephe/Gmail-Notifier#26]
Would it be simple to switch the base URL for all clicks to Gmail with `https://mail.google.com/mail/u/gmailnotifyuser@happysunshine.com/`?

Currently, Gmail Notifier sends users to https://mail.google.com, which redirects users to the inbox of the first account they used to sign in. This causes problems whenever I'm signed in with multiple accounts: I keep getting knocked back to that first account. (You'll notice a `/u/0/` in path of the URL: https://mail.google.com/mail/u/0/).

I'd hack this in myself, but I'm not sure how to pull the user's email address out of `GNMailAccountManager`.

Thanks! :beers:

**Comment by jashephe** [comment]
Yeah, the reason why you can't pull the email address out of GNMailAccountManager is because the application doesn't actually know your email address — it doesn't need that information to make requests; it only needs the OAuth2 tokens.  Since you brought this up, though, I thought to check the [inbox feed](https://mail.google.com/mail/feed/atom), which Gmail Notifier parses to get message data.  You'll notice that the `<title>` field contains what you're looking for: `<title>Gmail - Inbox for [email address here]</title>`.  You should be able to update the message parsing code to automatically load the email address from that.

I would look into this, but I've actually been working on a major re-write with multiple-account support.  I've put it on hold due to classwork, but I'm hoping to have it out by the end of the summer.  I've been holding off on pushing it to the repository because it isn't in working condition, but I could put it on a `devel` branch if you're interested.

**Comment by fny** [comment]
It would definitely be a feature to consider during the rewrite. No need to worry about it for this version though! I'm pretty sure I can hack a quick fix. \*coughproablyhardcodeitcough\*

**Comment by jashephe** [comment]
Hard coding is honestly what I would recommend.  If it leaves a bad taste in your mouth, you can always add a new text field to the preferences window, at least making it user-configurable.

And yes, it is already supported in the new version.  It's not something that could be easily back-ported, though — the new version is written in Swift, uses a custom OAuth2 implementation (also written in Swift), and targets the Gmail API, not the inbox atom feed.
