### ISSUE TITLE
Menubar icon statuses.

### ISSUE THREAD

**Issue by ux531** [jashephe/Gmail-Notifier#32]
Hi James, i have a question about the menubar icon. I replaced mine for new email with a red color icon so it's more prominent, but it doesn't show as red icon in the bar. I am on version 2.1.0. also the sound for new email does not trigger and i've checked the notification settings.

I have made some icons for you to elaborate and give feedback for all the states you've mentioned in your reply above.

[Gmail Notifier.pdf](https://github.com/jashephe/Gmail-Notifier/files/2052619/Gmail.Notifier.pdf)

If those can be changed by replacing icon files in the "Package Contents" folder as i actually did in my case, then why is the icon i use (the red one) not appearing as red.

Thanks for the great app James. I hope you have some time to reply.

**Comment by jashephe** [comment]
Hi @ux531, thanks for the feedback. Your issues with the icons can be traced to a single line in the codebase: [GNUtils.m#L39](https://github.com/jashephe/Gmail-Notifier/blob/master/Gmail%20Notifier/GNUtils.m#L39). Because the status bar icons are marked as [templates](https://developer.apple.com/documentation/appkit/nsimage/1520017-template?language=objc), Cocoa ignores color information and basically uses the black and transparent information as a mask. This is useful, because it allows the icons to automatically invert their color when, for instance, a user sets the system-wide dark UI theme (which, [you can see](https://github.com/jashephe/Gmail-Notifier/blame/master/Gmail%20Notifier/GNUtils.m#L39) is actually the reason why I added the `setTemplate` lines in the first place).

As noted in the README, I am sadly not in a position to maintain this anymore,but adding the functionality might not be too much work. You could:

- recompile the app without the `setTemplate` lines, allowing you to use your preferred icons directly (easiest, but might require some pain because of API updates in the last few years)
- recompile the app with the `setTemplate` lines, but add functionality for changing the icon color in the preferences (harder, but actually probably not that much more work)
- port all of these changes to the Swift version on the `devel` branch (haha)

Sorry I can't be of more help, but hopefully that at least explains what's going on!

**Comment by jashephe** [comment]
Sorry @ux531, I'm not aware of any direct alternatives. If you find one, let me know and I can link to it in the README. Cheers!
